# Generated by Django 4.1.2 on 2022-10-29 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_remove_song_artiste_id_song_artiste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='Artiste',
        ),
        migrations.AlterField(
            model_name='lyric',
            name='song_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.lyric'),
        ),
    ]
