# Generated by Django 4.1.2 on 2022-10-29 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_song_artiste_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artiste',
            old_name='ast_name',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='lyric',
            name='song_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artiste_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste'),
        ),
    ]
