# Generated by Django 4.1.2 on 2022-10-29 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_rename_ast_name_artiste_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artiste_id',
            new_name='artiste',
        ),
    ]
